const CATEGORY_LABELS={product:'通用产品','developer-tool':'程序员工具',game:'游戏',archive:'历史归档'}
const CATEGORY_COLORS={product:'#b9f24a','developer-tool':'#59dcc4',game:'#ffb35c',archive:'#82978f'}
const STATUS_LABELS={active:'已上线',developing:'开发中',closed:'已关闭',acquired:'已收购',unknown:'状态未知'}
const PAGE_SIZE=18
const state={all:[],filtered:[],visibleCount:PAGE_SIZE,metadata:{},query:'',category:'',status:'',year:'',city:''}
const el=id=>document.getElementById(id)
const formatNumber=value=>new Intl.NumberFormat('zh-CN').format(value)
const uniqueSorted=(values,compare=(a,b)=>String(a).localeCompare(String(b),'zh-CN'))=>[...new Set(values.filter(Boolean))].sort(compare)
const countBy=(records,key)=>records.reduce((map,item)=>map.set(item[key]||'未知',(map.get(item[key]||'未知')||0)+1),new Map())
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))

function fillSelect(select,entries,labeler=value=>value){const fragment=document.createDocumentFragment();for(const value of entries){const option=document.createElement('option');option.value=value;option.textContent=labeler(value);fragment.append(option)}select.append(fragment)}
function buildFilters(){fillSelect(el('category-filter'),uniqueSorted(state.all.map(item=>item.category)),value=>CATEGORY_LABELS[value]||value);fillSelect(el('status-filter'),uniqueSorted(state.all.map(item=>item.status)),value=>STATUS_LABELS[value]||value);fillSelect(el('year-filter'),uniqueSorted(state.all.map(item=>item.year),(a,b)=>b-a));fillSelect(el('city-filter'),uniqueSorted(state.all.map(item=>item.city)))}
function updateHeadlineMetrics(records){const developers=new Set(records.map(item=>item.developerName)).size;const cities=new Set(records.map(item=>item.city).filter(Boolean)).size;const active=records.filter(item=>['active','developing'].includes(item.status)).length;for(const [id,value] of Object.entries({'hero-total':records.length,'metric-products':records.length,'metric-developers':developers,'metric-cities':cities,'metric-active':active}))el(id).textContent=formatNumber(value)}

function renderYearChart(records){const counts=[...countBy(records.filter(item=>item.year),'year').entries()].sort((a,b)=>Number(a[0])-Number(b[0]));el('trend-total').textContent=`${formatNumber(records.length)} 条`;if(!counts.length){el('year-chart').innerHTML='<p class="empty-state">暂无年份数据</p>';return}const width=980,height=270,padding={top:24,right:18,bottom:36,left:42},innerWidth=width-padding.left-padding.right,innerHeight=height-padding.top-padding.bottom,max=Math.max(...counts.map(([,count])=>count),1),gap=Math.max(7,innerWidth/counts.length*.18),barWidth=Math.max(10,innerWidth/counts.length-gap),tickCount=4;const grid=Array.from({length:tickCount+1},(_,index)=>{const value=Math.round(max*(tickCount-index)/tickCount),y=padding.top+innerHeight*index/tickCount;return `<line class="chart-grid-line" x1="${padding.left}" y1="${y}" x2="${width-padding.right}" y2="${y}"/><text class="chart-axis-label" x="${padding.left-8}" y="${y+4}" text-anchor="end">${value}</text>`}).join('');const bars=counts.map(([year,count],index)=>{const x=padding.left+index*(innerWidth/counts.length)+gap/2,barHeight=innerHeight*count/max,y=padding.top+innerHeight-barHeight;return `<g><rect class="chart-bar" x="${x}" y="${y}" width="${barWidth}" height="${barHeight}" rx="5"><title>${year}: ${count} 条</title></rect><text class="chart-value" x="${x+barWidth/2}" y="${Math.max(13,y-7)}" text-anchor="middle">${count}</text><text class="chart-axis-label" x="${x+barWidth/2}" y="${height-11}" text-anchor="middle">${year}</text></g>`}).join('');el('year-chart').innerHTML=`<svg class="year-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="按年份统计产品收录数量">${grid}${bars}</svg>`}
function renderCategoryChart(records){const counts=[...countBy(records,'category').entries()].sort((a,b)=>b[1]-a[1]),total=Math.max(records.length,1);let cursor=0;const stops=counts.map(([category,count])=>{const start=cursor;cursor+=count/total*100;return `${CATEGORY_COLORS[category]||'#7e918a'} ${start}% ${cursor}%`});el('category-donut').style.background=`conic-gradient(${stops.join(',')})`;el('donut-total').textContent=formatNumber(records.length);el('category-legend').innerHTML=counts.map(([category,count])=>`<div class="legend-item"><span class="legend-dot" style="background:${CATEGORY_COLORS[category]||'#7e918a'}"></span><span>${escapeHtml(CATEGORY_LABELS[category]||category)}</span><strong>${count}</strong></div>`).join('')}
function renderCityChart(records){const counts=[...countBy(records.filter(item=>item.city),'city').entries()].sort((a,b)=>b[1]-a[1]).slice(0,8),max=Math.max(...counts.map(([,count])=>count),1);el('city-chart').innerHTML=counts.length?counts.map(([city,count])=>`<div class="bar-row"><span>${escapeHtml(city)}</span><div class="bar-track"><div class="bar-fill" style="width:${count/max*100}%"></div></div><strong>${count}</strong></div>`).join(''):'<p class="empty-state">当前筛选没有城市数据</p>'}
function renderStatusChart(records){const counts=countBy(records,'status');el('status-chart').innerHTML=['active','developing','closed','acquired','unknown'].filter(status=>counts.has(status)).map(status=>`<div class="status-item"><span>${STATUS_LABELS[status]}</span><strong>${formatNumber(counts.get(status))}</strong></div>`).join('')}
function renderDashboard(records){renderYearChart(records);renderCategoryChart(records);renderCityChart(records);renderStatusChart(records)}
function matches(record){const haystack=[record.productName,record.description,record.developerName,record.city,record.sourceFile].filter(Boolean).join(' ').toLowerCase();return(!state.query||haystack.includes(state.query.toLowerCase()))&&(!state.category||record.category===state.category)&&(!state.status||record.status===state.status)&&(!state.year||String(record.year)===state.year)&&(!state.city||record.city===state.city)}
function renderActiveFilters(){const entries=[['关键词',state.query],['类型',state.category?CATEGORY_LABELS[state.category]:''],['状态',state.status?STATUS_LABELS[state.status]:''],['年份',state.year],['城市',state.city]].filter(([,value])=>value);el('active-filters').innerHTML=entries.map(([label,value])=>`<span class="filter-chip">${label}：${escapeHtml(value)}</span>`).join('')}
function createProductCard(record){const fragment=el('product-template').content.cloneNode(true);fragment.querySelector('.category-badge').textContent=CATEGORY_LABELS[record.category]||record.category;const status=fragment.querySelector('.status-badge');status.textContent=STATUS_LABELS[record.status]||record.status;status.classList.add(record.status);fragment.querySelector('.product-name').textContent=record.productName;fragment.querySelector('.product-description').textContent=record.description||'暂无产品介绍';fragment.querySelector('.product-meta').innerHTML=[record.developerName,record.city,record.year].filter(Boolean).map(value=>`<span class="meta-pill">${escapeHtml(value)}</span>`).join('');fragment.querySelector('.source-date').textContent=record.date||'日期未知';const link=fragment.querySelector('.visit-link');if(record.productUrl)link.href=record.productUrl;else{link.textContent='链接不可用';link.setAttribute('aria-disabled','true')}return fragment}
function renderProducts(){const grid=el('product-grid');grid.innerHTML='';const visible=state.filtered.slice(0,state.visibleCount),fragment=document.createDocumentFragment();visible.forEach(record=>fragment.append(createProductCard(record)));grid.append(fragment);el('result-summary').textContent=`找到 ${formatNumber(state.filtered.length)} 条，当前显示 ${formatNumber(visible.length)} 条`;el('empty-state').hidden=state.filtered.length>0;el('load-more').hidden=visible.length>=state.filtered.length}
function applyFilters(){state.filtered=state.all.filter(matches);state.visibleCount=PAGE_SIZE;renderActiveFilters();renderDashboard(state.filtered);renderProducts()}
function bindEvents(){for(const [id,[stateKey,event]]of Object.entries({search:['query','input'],'category-filter':['category','change'],'status-filter':['status','change'],'year-filter':['year','change'],'city-filter':['city','change']})){el(id).addEventListener(event,e=>{state[stateKey]=e.target.value.trim();applyFilters()})}el('reset-filters').addEventListener('click',()=>{state.query=state.category=state.status=state.year=state.city='';for(const id of['search','category-filter','status-filter','year-filter','city-filter'])el(id).value='';applyFilters()});el('load-more').addEventListener('click',()=>{state.visibleCount+=PAGE_SIZE;renderProducts()});el('download-data').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({metadata:state.metadata,records:state.all},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='chinese-indie-developer-products.json';anchor.click();URL.revokeObjectURL(url)})}
async function init(){try{const response=await fetch('data/products.json');if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json();state.all=payload.records||[];state.filtered=state.all;state.metadata=payload.metadata||{};buildFilters();bindEvents();updateHeadlineMetrics(state.all);renderDashboard(state.all);renderProducts();const mode=state.metadata.snapshotMode==='full-upstream'?'完整上游快照':'MVP 示例快照';el('snapshot-note').textContent=`${mode} · ${formatNumber(state.all.length)} 条记录 · 来源保留至文件和行号`;el('generated-at').textContent=`数据生成时间：${new Date(state.metadata.generatedAt).toLocaleString('zh-CN')}`}catch(error){console.error(error);el('result-summary').textContent='数据加载失败';el('snapshot-note').textContent='无法读取 data/products.json，请先运行 npm run sync:data。';el('product-grid').innerHTML=`<div class="empty-state"><strong>数据加载失败</strong><p>${escapeHtml(error.message)}</p></div>`}}
init()
